#!/usr/bin/env sh
echo "pre-commit 훅 실행 중입니다."

# ESLint 검사 실행
echo "ESLint 검사 실행 중입니다."
npx next lint
RESULT=$?

# 결과 확인
if [ $RESULT -ne 0 ]; then
  echo "ESLint 검사 실패: 커밋이 중단되었습니다."
  exit 1
fi

echo "ESLint 검사 성공: 커밋을 진행합니다."
